version: "3"
services:

    nginx:
      build: requirements/nginx/
      container_name: nginx
#tty : true makes container permanent with interactive tty
      tty: true
      init: true
      ports:
        - 8000:80
        - 9000:9000
      # - 443:80
      networks: 
        - inception_network
      restart: always
      env_file: .env

    mariadb:
      depends_on: 
        - wordpress
      build: requirements/mariadb/
      container_name: mariadb
      tty: true
      init: true
      #ports:
      #  - 3306:3306
      networks: 
        - inception_network
      volumes:
       - wp_db:/var/lib/mysql
      restart: always
      env_file: .env

    wordpress:
      build: requirements/wordpress/
      container_name: wordpress-fpm
      tty: true
      init: true
      ports:
        - 8080:9000
      networks: 
        - inception_network
      volumes:
       - wp_files:/var/www/html
      restart: always
      env_file: .env

networks:
    inception_network:

#permissions handled by docker to prevent problems
volumes:
  wp_db:
    name: wp_db
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/$USER/wordpress/DB
  wp_files:
    name: wp-files
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/$USER/wordpress/wordpress
