version: "3"
services:

    nginx:
      build: requirements/nginx/
      container_name: nginx
#tty : true makes container permanent with interactive tty
      tty: true
      init: true
      ports:
        - 8080:80
        - 9000:9000
      # - 443:80
      networks: 
        - inception_network
      restart: always
      env_file: .env

    mariadb:
      depends_on: 
        - nginx
      build: requirements/mariadb/
      container_name: mariadb
      tty: true
      init: true
      #ports:
      #  - 3306:3306
      networks: 
        - inception_network
      volumes:
       - wp_db:/var/lib/mysql/
      restart: always
      env_file: .env

    wordpress:
      depends_on: 
        - mariadb
      build: requirements/wordpress/
      container_name: wordpress-fpm
      tty: true
      init: true
      #ports:
      #  - 9000:9000
      networks: 
        - inception_network
      #volumes:
      # - wp_files:
      restart: always
      env_file: .env

networks:
    inception_network:

#permissions handled by docker to prevent problems
volumes:
  wp_db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/mdesoeuv/wordpress/DB
  wp_files:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/mdesoeuv/wordpress/wordpress
