version: '3'
services:

    nginx:
      depends_on:
        - wordpress
      build: requirements/nginx/
      image: nginx
      container_name: nginx
      init: true
      ports:
        - 443:443
      networks: 
        - inception_network
      volumes:
        - wp_files:/var/www/html
      restart: always

    mariadb:
      build: 
        context: requirements/mariadb/
        args:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
      image: mariadb
      container_name: mariadb
      init: true
      networks: 
        - inception_network
      volumes:
       - wp_db:/var/lib/mysql
      restart: always

    wordpress:
      depends_on:
        - mariadb
      build:
        context: requirements/wordpress/
        args:
        - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
        - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
        - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
        - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
        - WORDPRESS_ADMIN=${WORDPRESS_ADMIN}
        - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD}
      image: wordpress
      container_name: wordpress
      init: true
      networks: 
        - inception_network
      volumes:
       - wp_files:/var/www/html
      restart: always
      env_file: requirements/wordpress/wp_env

networks:
    inception_network:

volumes:
  wp_db:
    name: wp_db
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/$USER/data/DB
  wp_files:
    name: wp_files
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/$USER/data/wordpress

#init: true => Run an init inside the container that forwards signals and reaps processes