version: '3'
services:

    nginx:
      depends_on:
        - wordpress
      build: requirements/nginx/
      container_name: nginx
      #tty: true
      init: true
      ports:
        - 443:443
      networks: 
        - inception_network
      volumes:
        - wp_files:/var/www/html
      restart: always
      env_file: .env

    mariadb:
      build: 
        context: requirements/mariadb/
        args:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
      container_name: mariadb
      #tty: true
      init: true
      command: --lower_case_table_names=2
      networks: 
        - inception_network
      volumes:
       - wp_db:/var/lib/mysql
      restart: always
      env_file: .env

    wordpress:
      depends_on:
        - mariadb
      build:
        context: requirements/wordpress/
        args:
        - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
        - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
        - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
        - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
        - WORDPRESS_ADMIN=${WORDPRESS_ADMIN}
        - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD}
      container_name: wordpress-fpm
      #tty: true
      init: true
      
      networks: 
        - inception_network
      volumes:
       - wp_files:/var/www/html
      restart: always
      env_file: .env

networks:
    inception_network:

volumes:
  wp_db:
    name: wp_db
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/$USER/wordpress/DB
  wp_files:
    name: wp-files
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/$USER/wordpress/wordpress
