version: "3"

services:

    nginx:

      build: requirements/nginx/
      #image: nginx_img
      container_name: nginx
      ports:
        - 8080:80
      # - 9000:9000
      # - 443:80
      networks: 
        - inception_network
      restart: always

    mariadb:

      depends_on: 
        - nginx
      build: requirements/nginx/
      #image: mariadb_img
      container_name: mariadb
      #ports:
      #  - 3306:3306
      networks: 
        - inception_network
      volumes:
       - wp_db:/var/lib/mysql/
      restart: always

    wordpress:
      depends_on: 
        - mariadb
      build: requirements/nginx/
      #image: wordpress_img
      container_name: wordpress-fpm
      ports:
        - 9000:9000
      networks: 
        - inception_network
      volumes:
       - wp_files:/var/www/html/
      restart: always

networks:
    inception_network:

#permissions handled by docker to prevent problems
volumes:
  wp_db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/mehdi/42/Cursus_42/wordpress/DB
  wp_files:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/mehdi/42/Cursus_42/wordpress/wordpress


